### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Toma400** [lukebemish/MysteryPotions#1]
Just as the title said, I tried to load world after adding the mod, but encountered crash. Here is log file:

[latest.log](https://github.com/lukebemish/MysteryPotions/files/12016291/latest.log)

Minecraft 1.20.1, Forge version 47.1.1.

**Comment by lukebemish** [comment]
Hmm. Looks like GML isn't setting up metaclass stuff quite right. I'll work to try to get that fixed on that end; hopefully the next update of GML will fix this.

**Comment by lukebemish** [comment]
This bug is set to be fixed by GroovyMC/GroovyModLoader#21. Once that is merged and the new version of GML released (which should happen tomorrow), updating GML will solve the issue

**Comment by lukebemish** [comment]
@Toma400 GML 4.0.4 fixes this
