### ISSUE TITLE
Crash after Mojang screen

### ISSUE THREAD

**Issue by dudeawsomeness1** [lukebemish/MysteryPotions#2]
>"Mod File mysterypotions-forge-1.20.1-1.0.0.jar needs language provider gml:1 or above to load   We have found none"

[crash-2023-11-09_12.56.30-fml.txt](https://github.com/lukebemish/MysteryPotions/files/13312396/crash-2023-11-09_12.56.30-fml.txt)

Minecraft 1.20.1
Forge 47.2.0

**Comment by lukebemish** [comment]
You need to install GML

**Comment by dudeawsomeness1** [comment]
> You need to install GML

Is this what you are talking about?
https://modrinth.com/mod/gml

**Comment by lukebemish** [comment]
Yes
